#!/bin/sh
set -e

USER="vpprestapi"
GROUP="vpprestapi"
VPPGROUP="vpp"

# Buat user dan group jika belum ada
if ! id -u "$USER" >/dev/null 2>&1; then
    echo "Creating system user $USER..."
    adduser --system --no-create-home --group --disabled-login --shell /usr/sbin/nologin "$USER"
fi

# Tambahkan user ke group vpp jika belum
if ! id "$USER" | grep -qw "$VPPGROUP"; then
    usermod -aG "$VPPGROUP" "$USER"
fi

systemctl daemon-reload

systemctl enable vpp-restapi
systemctl enable vpp-api-sock.path
systemctl enable load-vpp-config
systemctl enable generate-vpp-config.service
systemctl enable generate-vpp-config.timer

systemctl start vpp-restapi
systemctl start vpp-api-sock.path
systemctl start load-vpp-config
systemctl start generate-vpp-config.timer

exit 0
